name: getx_template
version: 1.0.0+1
publish_to: none
description: getx_template
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.1.1
  tdesign_flutter: ^0.1.3
  json_annotation: ^4.8.1
  talker_flutter: ^4.0.0
  talker_dio_logger: ^4.0.0
  flutter_screenutil: ^5.9.0
  intl: ^0.18.0
  path_provider: ^2.0.10
  path: ^1.8.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  dio: ^5.4.0
  universal_io: ^2.2.2
  flutter:
    sdk: flutter
  hive: ^2.2.3
  logging: ^1.2.0


dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  objectbox_generator: ^2.4.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

